name: Build and Deploy to Production

on:
  push:
    branches:
      - main  # Adjust this to your main development branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Adjust this to your preferred Node.js version

    - name: Install dependencies
      run: npm ci

    - name: Build application
      run: npm run build

    - name: Deploy to production branch
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'github-actions@github.com'
        git checkout -b production
        git add -f build
        git commit -m "Deploy to production"
        git push -f origin production
